learning_rate : 1.0e-4
n_steps : 2048
batch_size : 32
n_epochs : 10
gamma : 0.99
gae_lambda : 0.95
clip_range : 0.2
clip_range_vf : ~ # change to notice
normalize_advantage : True
ent_coef : 0.1
vf_coef : 0.5
max_grad_norm : 0.5
use_sde : False
sde_sample_freq : -1
target_kl : ~
stats_window_size : 100
seed : ~