!!python/object/new:utils.DotDic
dictitems:
  batch_size: 64
  clip_range: 0.2
  clip_range_vf: null
  ent_coef: 0.0
  gae_lambda: 0.95
  gamma: 0.99
  learning_rate: 0.0003
  max_grad_norm: 0.5
  n_epochs: 10
  n_steps: 2048
  normalize_advantage: true
  policy_kwargs:
    const_args: !!python/object/new:utils.DotDic
      dictitems:
        BW: 180000
        N0: -174
        Nb: 10
        Nrb: 3
        QoS_thr: 5
        bsloclist:
        - - 250
          - 500
        - - 750
          - 500
        fc: 6
        nChannel: 20
        nFBS: 0
        nMBS: 0
        nPBS: 1
        nRBs: 10
        nUEs: 20
        rFBS: null
        rMBS: null
        rPBS: 400
        txpowerFBSdBm: null
        txpowerMBSdBm: null
        txpowerPBSdBm: 50
        x_max: 1000
        y_max: 1000
  sde_sample_freq: -1
  seed: null
  stats_window_size: 100
  target_kl: null
  use_sde: false
  vf_coef: 0.5
